### PR TITLE
gatherSources() fix

### LINKED ISSUE #35: gatherSources() doesn't return expected file name for some imports
For 0x's npm imports (`import "@0x/some/thing/contr.sol"`) gatherSources() returns absolute path to file but solc expects a source named"@0x/some/thing/contr.sol".
gatherSources() should return solc-compatible names.

### PR DESCRIPTION
**Pull request by squadack**
should fix #35

### CODE REVIEW

File: src/solidity/utils.ts [hunk 1]
```diff
@@ -32,26 +32,35 @@ export function solidifyName(fileName: string): string {
...
   let result: ImportFile[] = [];
-  let queue = [];
+  let queue: { cwd: string; file: string }[] = [];
   let alreadyImported = new Set();
 
-  queue.push({ cwd: workingDir, file: what });
-  alreadyImported.add(solidifyName(what));
+  const absoluteWhat = path.resolve(workingDir, what);
+  queue.push({ cwd: workingDir, file: absoluteWhat });
+  alreadyImported.add(solidifyName(absoluteWhat));
```
Comment (cymerrad) [inline src/solidity/utils.ts]: I vividly remember our discussion regarding this algorithm, and I suggested more comments, explaining why this trick works and doesn't loop for example (I know it's because of initial path being an absolute path, but I know it *now*, I might forget this fact in the future and so may you).

File: src/solidity/utils.ts [hunk 2]
```diff
@@ -32,26 +32,35 @@ export function solidifyName(fileName: string): string {
 
 export async function gatherSources(
   what: string,
-  workingDir?: string,
+  workingDir: string = process.cwd(),
```
Comment (ritave) [inline src/solidity/utils.ts]: @cymerrad @squadack The requirement for the resolver is its ability to be used in browser context - we can't depend on any Node packages that don't work in browsers. We need to remove all `process` and etc. occurrences and inject them from the client side

https://stackoverflow.com/questions/3058/what-is-inversion-of-control

File: src/solidity/utils.ts [hunk 3]
```diff
@@ -32,26 +32,35 @@ export function solidifyName(fileName: string): string {
...
   while (queue.length > 0) {
     const fileData = queue.shift()!;
     const resolvedFile: ImportFile = await resolver.require(fileData.file, fileData.cwd);
     const foundImports = findImports(resolvedFile);
-    result.push(resolvedFile);
-    const filewd = path.dirname(resolvedFile.path);
+
+    // if imported path starts with '.' we assume it's relative and return it's absolute path
+    // if not - return the same name it was imported with
+    if (fileData.file[0] === ".") {
```
Comment (ritave) [inline src/solidity/utils.ts]: Not enough if the file is used in Windows context
https://www.npmjs.com/package/is-relative

Comment (ritave) [reply src/solidity/utils.ts]: Additionally, @Crypto-Punkers/developers it might be worth debating whether we always want to return an absolute path from the resolver in the first place

File: src/solidity/utils.ts [hunk 4]
```diff
@@ -32,26 +32,35 @@ export function solidifyName(fileName: string): string {
...
+      result.push(resolvedFile);
+    } else {
+      result.push({ path: fileData.file, source: resolvedFile.source });
+    }
+
+    const fileParentDir = path.dirname(resolvedFile.path);
     for (let i in foundImports) {
```
Comment (ritave) [inline src/solidity/utils.ts]: `const i in foundImports` should work

File: src/solidity/utils.ts [hunk 5]
```diff
@@ -32,26 +32,35 @@ export function solidifyName(fileName: string): string {
...
       const solidifiedName: string = solidifyName(foundImports[i]);
```
Comment (ritave) [inline src/solidity/utils.ts]: A learning comment - Typescript can resolve types implicitly and `const solidifiedName = solidifyName(...);` will also work and might be cleaner

File: src/solidity/utils.ts (hunk 3 above)
Comment (squadack) [reply src/solidity/utils.ts]: As per solidity documentation: "All path names are treated as absolute paths unless they start with the current . or the parent directory .. ."
https://solidity.readthedocs.io/en/v0.5.2/layout-of-source-files.html#paths

File: src/solidity/utils.ts (hunk 5 above)
Comment (squadack) [reply src/solidity/utils.ts]: solidifyName() will _probably_ get removed soon so I won't remove the type yet.

**Comment by squadack** [comment]
resolves #34
